<p>International Sizing Chart</p>
<table class="sizing-table">
  <tbody>
    <tr>
      <td>COUNTRY</td>
      <td>XXS</td>
      <td>XS</td>
      <td>S</td>
      <td>M</td>
      <td>L</td>
    </tr>
    <tr>
      <td>USA</td>
      <td>2</td>
      <td>4</td>
      <td>6</td>
      <td>8</td>
      <td>10</td>
    </tr>
    <tr>
      <td>ITALY</td>
      <td>38</td>
      <td>40</td>
      <td>42</td>
      <td>44</td>
      <td>46</td>
    </tr>
    <tr>
      <td>FRANCE</td>
      <td>34</td>
      <td>36</td>
      <td>38</td>
      <td>40</td>
      <td>42</td>
    </tr>
    <tr>
      <td>UK</td>
      <td>6</td>
      <td>8</td>
      <td>10</td>
      <td>12</td>
      <td>14</td>
    </tr>
    <tr>
      <td>JAPAN</td>
      <td>5</td>
      <td>7</td>
      <td>9</td>
      <td>11</td>
      <td>13</td>
    </tr>
    <tr>
      <td>NZ/AU</td>
      <td>6</td>
      <td>8</td>
      <td>10</td>
      <td>12</td>
      <td>14</td>
    </tr>
    <tr class="highlight">
      <td>GLORIA</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
